name: Staff
main: justbru00.staff.Staff		
version: 2.0
description: Shows staff.


commands:
 staff:
       description: Shows staff.   
 staffonline:
       description: Shows online staff.           
  