name: Staff
main: me.justbru00.staff.Staff		
version: 3.0
description: Shows staff.


commands:
 staff:
       description: Shows staff.   
 staffonline:
       description: Shows online staff.           
  